(()=>{
'use strict';
const V=11,SUB=['病理','生化','外科','生理','内科'],SH=['日','夜','出','休'];
const LOAD={日:{q:35,r:10,l:'轻量推进'},夜:{q:45,r:12,l:'中等强度'},出:{q:25,r:18,l:'复盘优先'},休:{q:80,r:20,l:'深度学习'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8),pad=n=>String(n).padStart(2,'0');
const fmt=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)},today=()=>fmt(new Date()),add=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return fmt(d)},diff=(a,b)=>Math.round((parse(b)-parse(a))/86400000),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultPapers=()=>Array.from({length:10},(_,i)=>({id:`year-${2017+i}`,name:`${2017+i} 年真题`,year:2017+i,questions:165,minutes:180,done:false}));
const DEFAULT={version:V,settings:{examDate:'2026-12-19',targetScore:220,currentAccuracy:59,anchor:'2026-08-31',anchorShift:'夜'},shifts:{'2026-08-30':'休'},activeSubjects:[],subjectProgress:{病理:0,生化:0,外科:0,生理:0,内科:0},mockPapers:defaultPapers(),nextMockId:null,tasks:[],records:[],customizedDates:{},lastBackupAt:null};
function clone(x){return JSON.parse(JSON.stringify(x))}
function normalize(src){src=src||{};const s=clone(DEFAULT),st=src.settings||{};s.settings.examDate=(st.examDate==='2026-12-20'?'2026-12-19':st.examDate)||s.settings.examDate;s.settings.targetScore=Number(st.targetScore)||220;s.settings.currentAccuracy=Number(st.currentAccuracy)||59;s.settings.anchor=st.anchor||st.cycleAnchor||s.settings.anchor;s.settings.anchorShift=st.anchorShift||s.settings.anchorShift;s.shifts=clone(src.shifts||src.customShifts||src.shiftOverrides||s.shifts);s.activeSubjects=(src.activeSubjects||[]).filter(x=>SUB.includes(x));s.subjectProgress={...s.subjectProgress,...(src.subjectProgress||{})};s.tasks=Array.isArray(src.tasks)?src.tasks.map(t=>t?.type==='mock'&&Number(t.questions)===180?{...t,questions:165}:t):[];s.records=Array.isArray(src.records)?src.records:[];s.customizedDates={...(src.customizedDates||src.customizedTaskDates||{})};s.lastBackupAt=src.lastBackupAt||st.lastBackupAt||null;const doneYears=new Set(src.completedMockYears||[]);if(Array.isArray(src.mockPapers)&&src.mockPapers.length)s.mockPapers=src.mockPapers.map((p,i)=>({id:p.id||`mock-${i}-${uid()}`,name:String(p.name||p.year||`套卷 ${i+1}`),year:Number(p.year)||null,questions:Number(p.questions)===180?165:(Number(p.questions)||165),minutes:Number(p.minutes)||180,done:!!p.done||(p.year&&doneYears.has(Number(p.year)))}));else s.mockPapers=defaultPapers().map(p=>({...p,done:doneYears.has(p.year)}));s.nextMockId=src.nextMockId&&s.mockPapers.some(p=>p.id===src.nextMockId&&!p.done)?src.nextMockId:null;return s}
function load(){for(const k of ['xizong-study-v11','xizong-study-v10','xizong-study-v9','xizong-study-v8','xizong-study-os-v1','xizong-study-v7']){try{const r=localStorage.getItem(k);if(r)return normalize(JSON.parse(r))}catch{}}return clone(DEFAULT)}
let state=load(),view='today',installPrompt=null;
function save(){state.version=V;localStorage.setItem('xizong-study-v11',JSON.stringify(state));try{const r=indexedDB.open('xizong-study-v11-db',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('state'))r.result.createObjectStore('state')};r.onsuccess=()=>{const tx=r.result.transaction('state','readwrite');tx.objectStore('state').put(clone(state),'main')}}catch{}}
function cycleShift(ds){let i=SH.indexOf(state.settings.anchorShift)+diff(state.settings.anchor,ds);i=((i%4)+4)%4;return SH[i]}
function shift(ds){return state.shifts[ds]||cycleShift(ds)}
function examDays(){return Math.max(0,diff(today(),state.settings.examDate))}
function activeSubjects(){const a=state.activeSubjects.filter(x=>SUB.includes(x));return a.length?a:[SUB.find(x=>(state.subjectProgress[x]||0)<100)||'内科']}
function nextPaper(){const chosen=state.nextMockId?state.mockPapers.find(p=>p.id===state.nextMockId&&!p.done):null;return chosen||state.mockPapers.find(p=>!p.done)||null}
function firstRest(ds){const d=parse(ds),off=(d.getDay()+6)%7,start=add(ds,-off);for(let i=0;i<7;i++){const x=add(start,i);if(shift(x)==='休')return x}return null}
function mockDay(ds){return !!nextPaper()&&shift(ds)==='休'&&firstRest(ds)===ds}
function ensureToday(){const ds=today();if(state.customizedDates[ds])return;const autos=state.tasks.filter(t=>t.auto&&t.date===ds);if(autos.length&&autos.every(t=>t.schema===V))return;state.tasks=state.tasks.filter(t=>!(t.auto&&t.date===ds&&!t.done));const l=LOAD[shift(ds)],paper=mockDay(ds)?nextPaper():null;state.tasks.push({id:uid(),date:ds,type:'review',name:'1. 错题复盘',questions:l.r,subject:'综合',done:false,auto:true,schema:V,order:1});if(paper){state.tasks.push({id:uid(),date:ds,type:'mock',name:`2. 套卷 · ${paper.name}`,questions:paper.questions,minutes:paper.minutes,subject:'西综',year:paper.year,mockId:paper.id,done:false,auto:true,schema:V,order:2})}else{const a=activeSubjects(),base=Math.floor(l.q/a.length),rem=l.q%a.length;a.forEach((s,i)=>state.tasks.push({id:uid(),date:ds,type:'practice',name:`${i+2}. 今日刷题 · ${s}`,questions:base+(i<rem?1:0),subject:s,done:false,auto:true,schema:V,order:i+2}))}save()}
function tasks(ds=today()){return state.tasks.filter(t=>t.date===ds).sort((a,b)=>(a.order??99)-(b.order??99))}
function scoredRecords(ds=null){return state.records.filter(r=>(!ds||r.date===ds)&&r.total>0&&r.type!=='review'&&r.type!=='study')}
function accuracy(ds=null){const rs=scoredRecords(ds),n=rs.reduce((a,r)=>a+r.total,0);return n?Math.round(rs.reduce((a,r)=>a+r.correct,0)/n*100):null}
function dayTotal(ds=today()){return state.records.filter(r=>r.date===ds&&r.type!=='study').reduce((a,r)=>a+(Number(r.total)||0),0)}
function totalAccuracy(){return accuracy()??state.settings.currentAccuracy}
function renderWeek(ds){const d=parse(ds),off=(d.getDay()+6)%7,labs=['一','二','三','四','五','六','日'];return labs.map((x,i)=>{const xds=add(ds,i-off),dd=parse(xds);return `<div class="day ${xds===ds?'today':''}"><span>${x}</span><b>${dd.getDate()}</b><span>${shift(xds)}</span></div>`}).join('')}
function icon(t){return({review:'复',practice:'题',mock:'模',study:'学'})[t]||'学'}
function taskHTML(t){const meta=t.type==='mock'?`${t.questions||165} 题 · ${t.minutes||180} 分钟`:t.type==='study'?'非刷题 · 不计题量/正确率':`${t.questions||0} 题`;const rec=['review','practice','mock'].includes(t.type);return `<div class="swipe" data-swipe="${t.id}"><div class="swipe-actions"><button class="swipe-edit" data-a="edit-task" data-id="${t.id}">编辑</button><button class="swipe-del" data-a="del-task" data-id="${t.id}">删除</button></div><div class="task ${t.done?'done':''}"><button class="check" data-a="toggle" data-id="${t.id}">${t.done?'✓':''}</button><div class="taskmain"><div class="task-title">${esc(t.name)}</div><div class="meta">${icon(t.type)} ${meta}${t.subject?` · ${esc(t.subject)}`:''}</div></div>${rec?`<button class="recordbtn" data-a="record" data-id="${t.id}">记录</button>`:''}</div></div>`}
function renderToday(){ensureToday();const ds=today(),ts=tasks(),done=ts.filter(t=>t.done).length,pct=ts.length?Math.round(done/ts.length*100):0,a=activeSubjects();return `<section class="card hero"><div class="hero-row"><div><div class="small muted">距离目标考试</div><div class="hero-num">${examDays()}<span style="font-size:18px"> 天</span></div><div class="small muted">目标西综 ${state.settings.targetScore} 分</div></div><div class="pill">${shift(ds)}班 · ${LOAD[shift(ds)].l}</div></div></section><div class="week">${renderWeek(ds)}</div><div class="section"><h2>今天只做这些</h2><button data-a="add-task">＋ 添加</button></div><section class="card">${ts.length?ts.map(taskHTML).join(''):'<div class="empty">今天还没有任务</div>'}<div style="margin-top:15px"><div class="progress"><i style="width:${pct}%"></i></div><div class="small muted" style="margin-top:7px">今日完成 ${done}/${ts.length} · ${pct}% · 左滑任务可编辑/删除</div></div></section><div class="stats"><div class="stat"><span class="small muted">今日总题量</span><b>${dayTotal(ds)}</b><div class="daily-note">含错题复盘</div></div><div class="stat"><span class="small muted">今日正确率</span><b>${accuracy(ds)===null?'—':accuracy(ds)+'%'}</b><div class="daily-note">仅刷题 / 套卷</div></div></div><div class="section"><h2>当前推进</h2></div><section class="card"><div class="listrow"><div><b>${a.join(' + ')}</b><div class="small muted">可多学科同步推进</div></div><span class="badge">${a.length} 门</span></div>${SUB.map(s=>`<div class="progress-row"><span>${s}</span><div class="progress"><i style="width:${state.subjectProgress[s]||0}%"></i></div><b>${state.subjectProgress[s]||0}%</b></div>`).join('')}</section><div class="stats"><div class="stat"><span class="small muted">累计记录</span><b>${state.records.length}</b></div><div class="stat"><span class="small muted">总正确率</span><b>${totalAccuracy()}%</b></div></div>`}
function renderPlan(){const a=activeSubjects(),n=nextPaper();return `<section class="card"><h2>学习安排</h2><p class="muted">普通学习日推进已选学科；套卷根据排班安排到休息日，并按下面的套卷清单顺序推进。</p><div class="callout">普通日：错题复盘 + 学科刷题；套卷日：错题复盘 + 套卷，不再推送今日刷题。</div></section><div class="section"><h2>当前推进学科</h2><span class="small muted">可多选</span></div><section class="card"><div class="subject-grid">${SUB.map(s=>`<label class="subject-choice"><input class="subject-check" type="checkbox" value="${s}" ${a.includes(s)?'checked':''}><span>${s}</span></label>`).join('')}</div><button class="btn primary" data-a="save-plan">保存推进学科与进度</button></section><div class="section"><h2>学科进度</h2><button type="button" onclick="document.querySelectorAll('.prog-range').forEach(x=>x.disabled=false);this.disabled=true;this.textContent='修改中'">修改进度</button></div><section class="card">${SUB.map(s=>`<div class="range-row" data-row="${s}"><b>${s}</b><div class="range-wrap"><input class="prog-range" data-subject="${s}" type="range" min="0" max="100" step="1" value="${state.subjectProgress[s]||0}" disabled><output>${state.subjectProgress[s]||0}%</output></div></div>`).join('')}<button class="btn primary" data-a="save-plan" style="margin-top:10px">保存推进学科与进度</button></section><div class="section"><h2>套卷清单</h2><span class="small muted">可添加</span></div><section class="card"><div class="grid2" style="align-items:end"><label style="margin:0">套卷名称<input id="mockName" placeholder="如：2025 二刷 / 模拟卷 A"></label><button class="btn secondary" data-a="add-mock">＋ 添加套卷</button></div><div class="small muted" style="margin:9px 0 12px">新增套卷默认 165 题、180 分钟。</div>${state.mockPapers.length?state.mockPapers.map(p=>`<div class="listrow"><div style="min-width:0"><b>${esc(p.name)}</b><div class="small muted">${p.done?'已完成':(n?.id===p.id?'下一套':'待安排')} · ${p.questions} 题</div></div><div class="mock-actions"><button class="mockbtn ${n?.id===p.id&&!p.done?'done':''}" data-a="set-next-mock" data-id="${p.id}" ${p.done?'disabled':''}>${n?.id===p.id&&!p.done?'✓ 下一套':'设为下一套'}</button><button class="mockbtn ${p.done?'done':''}" data-a="toggle-mock" data-id="${p.id}">${p.done?'✓ 已完成':'标记完成'}</button><button class="xbtn" data-a="del-mock" data-id="${p.id}">×</button></div></div>`).join(''):'<div class="empty">还没有套卷</div>'}</section>`}
function recordHTML(r){const review=r.type==='review';const score=review?`复盘 ${r.total||0} 题`:(r.type==='study'?'西综复习':`${r.total||0} 题 · ${r.total?Math.round((r.correct||0)/r.total*100):0}%`);return `<div class="record"><div class="rhead"><div><b>${esc(r.subject||'综合')}${r.year?` · ${r.year}`:''}</b><div class="small muted">${r.date}${r.minutes?` · ${r.minutes} 分钟`:''}</div></div><span class="score">${score}</span></div>${r.note?`<div style="margin-top:7px">${esc(r.note)}</div>`:''}</div>`}
function renderRecords(){const rs=[...state.records].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));return `<div class="stats"><div class="stat"><span class="small muted">总正确率</span><b>${totalAccuracy()}%</b></div><div class="stat"><span class="small muted">累计题量</span><b>${state.records.filter(r=>r.type!=='study').reduce((a,r)=>a+(Number(r.total)||0),0)}</b></div></div><div class="section"><h2>最近记录</h2><button data-a="record">＋ 录入</button></div><section class="card">${rs.length?rs.slice(0,40).map(recordHTML).join(''):'<div class="empty">还没有记录</div>'}</section>`}
function renderReview(){const rs=state.records.filter(r=>r.type==='review').sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')),notes=state.records.filter(r=>r.note);return `<div class="section"><h2>错题复盘记录</h2></div><section class="card">${rs.length?rs.slice(0,30).map(recordHTML).join(''):'<div class="empty">复盘任务完成后点“记录”，这里会保存题量、用时和备注，不计算正确率。</div>'}</section><div class="section"><h2>错题 / 备注</h2></div><section class="card">${notes.length?notes.slice().reverse().slice(0,30).map(r=>`<div class="record"><b>${esc(r.subject||'综合')}</b><div class="small muted">${r.date}</div><div style="margin-top:7px">${esc(r.note)}</div></div>`).join(''):'<div class="empty">暂无备注</div>'}</section>`}
function scheduleRows(){return Array.from({length:14},(_,i)=>{const ds=add(today(),i),d=parse(ds);return `<div class="shift-edit"><div><b>${d.getMonth()+1}/${d.getDate()} · 周${'日一二三四五六'[d.getDay()]}</b><div class="small muted">${state.shifts[ds]?'已修改':''}</div></div><select class="shift-select" data-date="${ds}">${SH.map(s=>`<option ${s===shift(ds)?'selected':''}>${s}</option>`).join('')}</select></div>`}).join('')}
function renderMe(){const ds=today();return `<section class="card"><h2>今日排班</h2><p class="small muted">点击班次即可修改今天。</p><div class="shift-row">${SH.map(s=>`<button class="shift-btn ${s===shift(ds)?'active':''}" data-a="today-shift" data-shift="${s}">${s}</button>`).join('')}</div></section><section class="card"><h2>排班编辑</h2><p class="small muted">未来 14 天可逐日修改，保存后会影响对应日期的学习任务安排。</p>${scheduleRows()}<button class="btn primary" data-a="save-schedule" style="margin-top:12px">保存未来 14 天排班</button></section><section class="card"><h2>学习设置</h2><label>目标西综分数<input id="setTarget" type="number" min="0" max="300" value="${state.settings.targetScore}"></label><label>考试日期<input id="setExam" type="date" value="${state.settings.examDate}"></label><button class="btn primary" data-a="save-settings">保存设置</button></section><section class="card"><h2>本机数据</h2><p class="small muted">数据保存在当前手机。建议定期导出备份。</p><button class="btn secondary" data-a="export" style="margin-bottom:9px">导出备份</button><button class="btn secondary" data-a="import" style="margin-bottom:9px">导入备份</button><input id="importFile" class="hidden" type="file" accept="application/json"><button class="btn secondary danger" data-a="reset">清空数据</button></section><section class="card"><h2>离线状态</h2><div class="listrow"><div><b>${navigator.onLine?'当前有网络':'当前离线'}</b><div class="small muted">安装后核心页面可离线打开</div></div><span class="badge">PWA v12</span></div></section>`}
function render(){const map={today:renderToday,plan:renderPlan,records:renderRecords,review:renderReview,me:renderMe};$('#view').innerHTML=map[view]();const d=new Date();$('#dateText').textContent=`${d.getMonth()+1}月${d.getDate()}日 · 周${'日一二三四五六'[d.getDay()]}`;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function toast(x){const e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function markMock(task,done){if(task?.type!=='mock')return;const p=state.mockPapers.find(x=>x.id===task.mockId)||state.mockPapers.find(x=>x.year&&x.year===task.year);if(p){p.done=done;if(done&&state.nextMockId===p.id)state.nextMockId=null}}
function openRecord(id=null){const t=id?state.tasks.find(x=>x.id===id):null,rev=t?.type==='review';$('#recordTaskId').value=id||'';$('#recordTitle').textContent=t?.type==='mock'?'记录套卷':rev?'记录错题复盘':'记录刷题';$('#rSubject').innerHTML=[...SUB,'西综','综合'].map(s=>`<option ${t?.subject===s?'selected':''}>${s}</option>`).join('');$('#rYear').value=t?.year||'';$('#rTotal').value=t?.questions||'';$('#rCorrect').value='';$('#correctWrap').style.display=rev?'none':'';$('#rMinutes').value=t?.type==='mock'?(t.minutes||180):'';$('#rNote').value='';$('#recordDialog').showModal()}
function syncTaskType(){const study=$('#tType').value==='study';$('#qWrap').style.display=study?'none':'';if(study)$('#tQuestions').value=''}
function openTask(id=null){const t=id?state.tasks.find(x=>x.id===id):null;$('#taskId').value=t?.id||'';$('#taskTitle').textContent=t?'编辑任务':'添加任务';$('#tDate').value=t?.date||today();$('#tName').value=t?.name||'';$('#tType').value=t?.type||'practice';$('#tQuestions').value=t?.questions??'';syncTaskType();$('#taskDialog').showModal()}
function savePlan(){const selected=$$('.subject-check:checked').map(x=>x.value).filter(x=>SUB.includes(x));if(!selected.length)return toast('至少选择 1 门学科');$$('.prog-range').forEach(x=>state.subjectProgress[x.dataset.subject]=clamp(Number(x.value)||0,0,100));state.activeSubjects=selected;state.tasks=state.tasks.filter(t=>!(t.auto&&t.date===today()&&!t.done));save();render();toast('学习计划已保存')}
function exportData(){state.lastBackupAt=new Date().toISOString();save();const blob=new Blob([JSON.stringify({app:'西综作战室',version:V,data:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`西综作战室备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(file){try{const p=JSON.parse(await file.text());state=normalize(p.data||p);save();render();toast('备份已恢复')}catch{toast('备份文件无法识别')}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;render();return}const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a,id=b.dataset.id;if(a==='add-task')openTask();if(a==='edit-task')openTask(id);if(a==='record')openRecord(id||null);if(a==='toggle'){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;markMock(t,t.done);save();render()}}if(a==='del-task'){const t=state.tasks.find(x=>x.id===id);if(t&&confirm(`删除“${t.name}”？`)){if(t.auto)state.customizedDates[t.date]=true;state.tasks=state.tasks.filter(x=>x.id!==id);save();render();toast('任务已删除')}}if(a==='save-plan')savePlan();if(a==='today-shift'){state.shifts[today()]=b.dataset.shift;state.tasks=state.tasks.filter(t=>!(t.auto&&t.date===today()&&!t.done));save();render();toast('今日排班已修改')}if(a==='save-schedule'){$$('.shift-select').forEach(x=>state.shifts[x.dataset.date]=x.value);state.tasks=state.tasks.filter(t=>!t.auto||t.done||t.date<today());save();render();toast('排班已保存')}if(a==='set-next-mock'){const p=state.mockPapers.find(x=>x.id===id);if(p&&!p.done){state.nextMockId=p.id;state.tasks=state.tasks.filter(t=>!(t.auto&&t.date===today()&&!t.done));save();render();toast('已设为下一套')}}if(a==='toggle-mock'){const p=state.mockPapers.find(x=>x.id===id);if(p){p.done=!p.done;if(p.done&&state.nextMockId===p.id)state.nextMockId=null;state.tasks=state.tasks.filter(t=>!(t.auto&&t.date===today()&&!t.done));save();render()}}if(a==='add-mock'){const name=$('#mockName')?.value.trim();if(!name)return toast('请输入套卷名称');state.mockPapers.push({id:uid(),name,year:null,questions:165,minutes:180,done:false});save();render();toast('套卷已添加')}if(a==='del-mock'){const p=state.mockPapers.find(x=>x.id===id);if(p&&confirm(`删除“${p.name}”吗？`)){if(state.nextMockId===id)state.nextMockId=null;state.mockPapers=state.mockPapers.filter(x=>x.id!==id);state.tasks=state.tasks.filter(t=>t.mockId!==id||t.done);save();render()}}if(a==='save-settings'){state.settings.targetScore=Number($('#setTarget').value)||220;state.settings.examDate=$('#setExam').value||state.settings.examDate;save();render();toast('设置已保存')}if(a==='export')exportData();if(a==='import')$('#importFile').click();if(a==='reset'&&confirm('确定清空全部学习数据吗？')){state=clone(DEFAULT);save();render();toast('已清空')}});
$('#recordForm').addEventListener('submit',e=>{e.preventDefault();const tid=$('#recordTaskId').value,t=tid?state.tasks.find(x=>x.id===tid):null,rev=t?.type==='review',total=Number($('#rTotal').value)||0,correct=rev?0:(Number($('#rCorrect').value)||0);if(!rev&&correct>total)return toast('正确数不能大于题数');const r={id:uid(),date:today(),type:t?.type||'practice',subject:$('#rSubject').value,year:Number($('#rYear').value)||null,total,correct,minutes:Number($('#rMinutes').value)||0,note:$('#rNote').value.trim(),createdAt:new Date().toISOString()};state.records.push(r);if(t){t.done=true;markMock(t,true)}save();$('#recordDialog').close();render();toast(rev?`已记录复盘 ${total} 题`:`已记录 · ${total?Math.round(correct/total*100):0}%`)});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#taskId').value,type=$('#tType').value,v={date:$('#tDate').value,name:$('#tName').value.trim(),type,questions:type==='study'?0:(Number($('#tQuestions').value)||0),auto:false,userCustomized:true};if(!v.name)return toast('请输入任务名称');if(id){const t=state.tasks.find(x=>x.id===id);if(t){state.customizedDates[t.date]=true;Object.assign(t,v)}}else state.tasks.push({id:uid(),...v,done:false});save();$('#taskDialog').close();render();toast(id?'任务已修改':'任务已添加')});
$('#tType').addEventListener('change',syncTaskType);$('#closeRecord').addEventListener('click',()=>$('#recordDialog').close());$('#closeTask').addEventListener('click',()=>$('#taskDialog').close());document.addEventListener('input',e=>{if(e.target.classList.contains('prog-range')){const row=e.target.closest('.range-row'),v=e.target.value;row.querySelector('output').textContent=v+'%';void 0}});document.addEventListener('change',e=>{if(e.target.id==='importFile'&&e.target.files[0])importData(e.target.files[0])});
let sx=0,sy=0,row=null,drag=false;document.addEventListener('touchstart',e=>{const r=e.target.closest('.swipe');$$('.swipe.open').forEach(x=>{if(x!==r)x.classList.remove('open')});if(!r)return;const t=e.touches[0];sx=t.clientX;sy=t.clientY;row=r;drag=false},{passive:true});document.addEventListener('touchmove',e=>{if(!row)return;const t=e.touches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){drag=true;e.preventDefault()}},{passive:false});document.addEventListener('touchend',e=>{if(!row)return;const dx=e.changedTouches[0].clientX-sx;if(drag)row.classList.toggle('open',dx<-35);row=null;drag=false},{passive:true});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')});window.addEventListener('online',render);window.addEventListener('offline',render);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));try{navigator.storage?.persist?.()}catch{}save();render();
})();