(()=>{
'use strict';
const STORE_KEY='xizong-study-v11',DB_NAME='xizong-study-v11-db',UNDO_KEY='xizong-study-undo-v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const parse=s=>{const [y,m,d]=String(s||today()).split('-').map(Number);return new Date(y,m-1,d,12)};
const add=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const dayDiff=(a,b)=>Math.round((parse(b)-parse(a))/86400000);
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE_KEY)||'null')}catch{return null}};
function mirror(state){try{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('state'))r.result.createObjectStore('state')};r.onsuccess=()=>{const tx=r.result.transaction('state','readwrite');tx.objectStore('state').put(JSON.parse(JSON.stringify(state)),'main')}}catch{}}
function write(state){localStorage.setItem(STORE_KEY,JSON.stringify(state));mirror(state)}
function uid(prefix='ux'){return `${prefix}-${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`}
function findItem(state,id){return (state?.rollingReviews||[]).find(r=>r.id===id)}
function findNode(item,index){return item?.nodes?.find(n=>Number(n.index)===Number(index))}
function toast(msg){let el=$('#uxToast');if(!el){el=document.createElement('div');el.id='uxToast';el.className='ux-toast';document.body.appendChild(el)}el.innerHTML=`<span>${esc(msg)}</span>`;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function dueLabel(date){const d=dayDiff(date,today());if(d===0)return {text:'今日到期',cls:'today'};if(d>0)return {text:`逾期${d}天`,cls:'overdue'};return {text:`还有${Math.abs(d)}天`,cls:'future'}}
function rollingDue(state){return (state?.rollingReviews||[]).filter(r=>!r.paused).flatMap(r=>(r.nodes||[]).filter(n=>n.status==='pending'&&n.date<=today()).map(node=>({item:r,node}))).sort((a,b)=>a.node.date.localeCompare(b.node.date))}
function nextNode(item){return (item.nodes||[]).find(n=>n.status==='pending')||null}
function groupFor(item){if(item.subject==='外科')return 'surgery';if(item.subject==='生化')return 'biochem';return 'core'}
const GROUPS=[['core','病理 + 生理 + 内科'],['surgery','外科'],['biochem','生化']];

function stashUndo(label){const state=read();if(!state)return;try{sessionStorage.setItem(UNDO_KEY,JSON.stringify({label,state,at:Date.now()}))}catch{}}
function showUndo(){let p;try{p=JSON.parse(sessionStorage.getItem(UNDO_KEY)||'null')}catch{}if(!p||Date.now()-p.at>12000){sessionStorage.removeItem(UNDO_KEY);return}let el=$('#uxUndo');if(!el){el=document.createElement('div');el.id='uxUndo';el.className='ux-undo';document.body.appendChild(el)}el.innerHTML=`<span>${esc(p.label||'已更新')}</span><button data-ux="undo">撤销</button>`;el.classList.add('show');clearTimeout(showUndo.t);showUndo.t=setTimeout(()=>{el.classList.remove('show');sessionStorage.removeItem(UNDO_KEY)},9000)}
function undo(){let p;try{p=JSON.parse(sessionStorage.getItem(UNDO_KEY)||'null')}catch{}if(!p?.state)return;write(p.state);sessionStorage.removeItem(UNDO_KEY);location.reload()}

function rollingRecord(state,item,node,minutes=0,noteSuffix=''){state.records=Array.isArray(state.records)?state.records:[];if(node&&state.records.some(r=>r.rollingId===item.id&&Number(r.rollingIndex)===Number(node.index)))return;state.records.push({id:uid('rollrec'),date:today(),type:'rolling',subject:item.subject||'综合',year:null,total:0,correct:0,minutes:Number(minutes)||0,note:`${item.name}${node?` · 第${node.index}轮`:''}${noteSuffix}`,createdAt:new Date().toISOString(),rollingId:item.id,rollingIndex:node?Number(node.index):null})}
function markLinkedTask(state,item,node,done=true){for(const t of state.tasks||[]){if(t.type==='rolling'&&t.rollingId===item.id&&Number(t.rollingIndex)===Number(node.index))t.done=done}}
function selectedDueKeys(){return $$('.ux-due-check:checked').map(x=>x.value)}
function keyParts(v){const cut=v.lastIndexOf(':');return [v.slice(0,cut),Number(v.slice(cut+1))]}
function mutateSelected(kind){const keys=selectedDueKeys();if(!keys.length)return toast('先选择要处理的滚动项目');const state=read();if(!state)return;stashUndo(kind==='complete'?'已批量完成':kind==='delay'?'已批量顺延':'已批量暂停');const itemIds=new Set();for(const key of keys){const [id,index]=keyParts(key),item=findItem(state,id),node=findNode(item,index);if(!item||!node)continue;itemIds.add(id);if(kind==='complete'){node.status='done';node.completedAt=new Date().toISOString();node.minutes=0;rollingRecord(state,item,node,0);markLinkedTask(state,item,node,true)}else if(kind==='delay'){node.date=add(node.date,1);state.tasks=(state.tasks||[]).filter(t=>!(t.type==='rolling'&&t.rollingId===id&&Number(t.rollingIndex)===index&&!t.done))}}
  if(kind==='pause'){for(const id of itemIds){const item=findItem(state,id);if(item)item.paused=true}state.tasks=(state.tasks||[]).filter(t=>!(t.type==='rolling'&&itemIds.has(t.rollingId)&&!t.done))}
  write(state);location.reload()}
function mutateOne(action,id,index){const state=read(),item=findItem(state,id),node=findNode(item,index);if(!state||!item||!node)return;stashUndo(action==='complete'?'滚动复习已完成':action==='delay'?'滚动复习已顺延':'本轮已跳过');if(action==='complete'){const raw=prompt('本次复习用时（分钟，可留空）','');if(raw===null){sessionStorage.removeItem(UNDO_KEY);return}const minutes=Math.max(0,Number(raw)||0);node.status='done';node.completedAt=new Date().toISOString();node.minutes=minutes;rollingRecord(state,item,node,minutes);markLinkedTask(state,item,node,true)}else if(action==='delay'){node.date=add(node.date,1);state.tasks=(state.tasks||[]).filter(t=>!(t.type==='rolling'&&t.rollingId===id&&Number(t.rollingIndex)===Number(index)&&!t.done))}else{node.status='skipped';node.completedAt=new Date().toISOString();markLinkedTask(state,item,node,true)}write(state);location.reload()}
function togglePause(id){const state=read(),item=findItem(state,id);if(!item)return;stashUndo(item.paused?'已恢复滚动':'已暂停滚动');item.paused=!item.paused;if(item.paused)state.tasks=(state.tasks||[]).filter(t=>!(t.type==='rolling'&&t.rollingId===id&&!t.done));write(state);location.reload()}
function deleteRollingProject(id){const state=read(),item=findItem(state,id);if(!item)return;const done=(item.nodes||[]).filter(n=>n.status==='done').length,records=(state.records||[]).filter(r=>r.rollingId===id).length;if(!confirm(`删除“${item.name}”的滚动计划？\n已完成 ${done} 轮，历史学习记录 ${records} 条将保留。`))return;stashUndo('滚动项目已删除');state.rollingReviews=(state.rollingReviews||[]).filter(r=>r.id!==id);state.tasks=(state.tasks||[]).filter(t=>t.rollingId!==id||t.done);write(state);location.reload()}

function dueRow(item,node){const s=dueLabel(node.date);return `<div class="ux-due-row"><label class="ux-check"><input class="ux-due-check" type="checkbox" value="${esc(item.id)}:${node.index}"><span></span></label><div class="ux-grow"><b>${esc(item.name)}</b><div class="small muted">${esc(item.subject||'综合')} · 第${node.index}轮 · 原定 ${node.date}</div></div><span class="ux-status ${s.cls}">${s.text}</span><div class="ux-inline-actions"><button data-ux="complete-one" data-id="${esc(item.id)}" data-index="${node.index}">完成</button><button data-ux="delay-one" data-id="${esc(item.id)}" data-index="${node.index}">+1天</button><button data-ux="skip-one" data-id="${esc(item.id)}" data-index="${node.index}">跳过</button></div></div>`}
function projectRow(item){const nx=nextNode(item),done=(item.nodes||[]).filter(n=>n.status==='done').length,skip=(item.nodes||[]).filter(n=>n.status==='skipped').length,s=nx?dueLabel(nx.date):null;return `<div class="ux-project-row"><div class="ux-grow"><b>${esc(item.name)}</b><div class="small muted">${esc(item.group||'')} · 完成 ${done}/${(item.nodes||[]).length}${skip?` · 跳过 ${skip}`:''}${nx?` · 下次 ${nx.date}`:' · 已完成全部轮次'}</div></div>${s?`<span class="ux-status ${s.cls}">${s.text}</span>`:'<span class="ux-status done">已完成</span>'}<button class="ux-mini" data-ux="pause-project" data-id="${esc(item.id)}">${item.paused?'继续':'暂停'}</button><button class="ux-mini danger" data-ux="delete-project" data-id="${esc(item.id)}">删除</button></div>`}
function renderRollingEnhanced(){const nav=$('#nav [data-view="rolling"].active'),view=$('#view');if(!nav||!view||view.dataset.uxRolling==='1')return;const state=read();if(!state)return;const due=rollingDue(state),over=due.filter(x=>x.node.date<today()),extra=(state.records||[]).filter(r=>r.type==='rolling'&&!r.rollingIndex&&String(r.note||'').includes('额外复习')),extraMin=extra.reduce((a,r)=>a+(Number(r.minutes)||0),0),expanded=sessionStorage.getItem('ux-roll-expanded')==='1',shown=expanded?due:due.slice(0,5);const groups=GROUPS.map(([id,label])=>{const items=(state.rollingReviews||[]).filter(r=>groupFor(r)===id).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));return `<details class="ux-group" ${id==='core'?'open':''}><summary>${label}<span>${items.length}</span></summary>${items.length?items.map(projectRow).join(''):'<div class="empty">暂无项目</div>'}</details>`}).join('');view.dataset.uxRolling='1';view.innerHTML=`<div class="ux-rolling-root"><div class="stats ux-stats4"><div class="stat"><span class="small muted">今日到期</span><b>${due.length-over.length}</b></div><div class="stat"><span class="small muted">逾期</span><b>${over.length}</b></div><div class="stat"><span class="small muted">滚动项目</span><b>${(state.rollingReviews||[]).length}</b></div><div class="stat"><span class="small muted">额外复习</span><b>${extra.length}<small> 次</small></b><div class="daily-note">${extraMin} min</div></div></div><div class="section"><h2>今日滚动</h2><button data-a="add-rolling">＋ 添加</button></div><section class="card ux-due-card">${due.length?`<div class="ux-batch"><button data-ux="select-all">全选</button><button data-ux="batch-complete">批量完成</button><button data-ux="batch-delay">顺延1天</button><button data-ux="batch-pause">批量暂停</button></div>${shown.map(({item,node})=>dueRow(item,node)).join('')}${due.length>5?`<button class="ux-more" data-ux="toggle-due">${expanded?'收起':'查看全部 '+due.length+' 项'}</button>`:''}`:'<div class="empty">今天没有到期或逾期的滚动复习</div>'}</section><div class="section"><h2>滚动项目</h2><span class="small muted">按三大类折叠</span></div>${groups}<button class="btn primary" data-a="add-rolling">＋ 添加滚动复习</button></div>`}

function todayRollingEnhance(){const nav=$('#nav [data-view="today"].active');if(!nav)return;const state=read();if(!state)return;const rows=[];for(const t of (state.tasks||[]).filter(t=>t.date===today()&&t.type==='rolling')){const row=document.querySelector(`[data-swipe="${CSS.escape(t.id)}"]`);if(!row)continue;rows.push({t,row});if(!row.querySelector('.ux-task-status')){const item=findItem(state,t.rollingId),node=findNode(item,t.rollingIndex),s=node?dueLabel(node.date):{text:t.rollingInitial?'新加入':'滚动复习',cls:'today'},badge=document.createElement('span');badge.className=`ux-task-status ux-status ${s.cls}`;badge.textContent=s.text;row.querySelector('.task')?.insertBefore(badge,row.querySelector('[data-a="start-task"], [data-a="record"]')||null)}}
  const pending=rows.filter(x=>!x.t.done);if(pending.length<=5)return;const expanded=sessionStorage.getItem('ux-today-roll-expanded')==='1';pending.slice(5).forEach(x=>x.row.classList.toggle('ux-hidden',!expanded));const card=rows[0]?.row.closest('.card');if(card&&!card.querySelector('.ux-backlog')){const due=rollingDue(state),over=due.filter(x=>x.node.date<today()).length,bar=document.createElement('div');bar.className='ux-backlog';bar.innerHTML=`<div><b>滚动复习 ${pending.length} 项</b><div class="small muted">${over?`逾期 ${over} 项 · `:''}默认先显示前 5 项</div></div><button data-ux="toggle-today">${expanded?'收起':'展开全部'}</button>`;card.insertBefore(bar,card.firstChild)}}

function mockTrendEnhance(){const nav=$('#nav [data-view="records"].active'),view=$('#view');if(!nav||!view||view.querySelector('.ux-mock-trend'))return;const state=read();if(!state)return;const mocks=(state.records||[]).filter(r=>r.type==='mock'&&Number(r.total)>0).sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(-10);if(!mocks.length)return;const sec=document.createElement('section');sec.className='card ux-mock-trend';sec.innerHTML=`<div class="ux-card-title"><h2>套卷正确率趋势</h2><span class="small muted">最近 ${mocks.length} 套</span></div>${mocks.map(r=>{const acc=Math.round((Number(r.correct)||0)/(Number(r.total)||165)*100);return `<div class="ux-trend-row"><span>${esc(r.year||r.date||'套卷')}</span><div class="ux-trend"><i style="width:${acc}%"></i></div><b>${acc}%</b><small>${Number(r.minutes)||0} min</small></div>`}).join('')}`;const first=view.querySelector('.stats');first?.after(sec)}

function backupAndCsvEnhance(){const nav=$('#nav [data-view="me"].active');if(!nav)return;const state=read();if(!state)return;const card=$$('#view .card').find(c=>c.querySelector('h2')?.textContent.trim()==='本机数据');if(!card||card.dataset.uxData==='1')return;card.dataset.uxData='1';const last=state.lastBackupAt?new Date(state.lastBackupAt):null,days=last?Math.floor((Date.now()-last.getTime())/86400000):Infinity,meaningful=(state.records||[]).length+(state.tasks||[]).length+(state.rollingReviews||[]).length;if(meaningful&&days>=14){const box=document.createElement('div');box.className='ux-backup-reminder';box.innerHTML=`<b>${last?`距上次备份已 ${days} 天`:'还没有导出过备份'}</b><div class="small muted">建议定期保存 JSON 备份，避免浏览器数据被清理后无法恢复。</div><button class="ux-mini" data-a="export">立即备份</button>`;card.insertBefore(box,card.querySelector('button'))}const btn=document.createElement('button');btn.className='btn secondary';btn.dataset.ux='export-csv';btn.style.marginBottom='9px';btn.textContent='导出学习记录 CSV';const importBtn=[...card.querySelectorAll('button')].find(b=>b.dataset.a==='import');card.insertBefore(btn,importBtn||null)}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function exportCsv(){const state=read();if(!state)return;const rows=[['日期','类型','学科','内容/备注','用时(分钟)','套卷题数','正确数','正确率']];for(const r of (state.records||[]).slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''))){const type=r.type==='mock'?'套卷':r.type==='rolling'?'滚动复习':r.type==='review'?'错题复盘':'学习',acc=r.type==='mock'&&Number(r.total)>0?`${Math.round((Number(r.correct)||0)/Number(r.total)*100)}%`:'';rows.push([r.date,type,r.subject||'综合',r.note||'',Number(r.minutes)||0,r.type==='mock'?(r.total||165):'',r.type==='mock'?(r.correct??''):'',acc])}const csv='\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`西综学习记录-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV 已导出')}

function autoTaskName(){const type=$('#tType')?.value,name=$('#tName');if(!name)return;const map={practice:'今日学习',review:'错题复盘',mock:'套卷'};if(!map[type])return;const known=['今日学习','错题复盘','套卷'];if(!name.value.trim()||name.dataset.uxAuto==='1'||known.includes(name.value.trim())){name.value=map[type];name.dataset.uxAuto='1'}}
function removeLegacyStudyOption(){const sel=$('#tType');if(!sel)return;sel.querySelector('option[value="study"]')?.remove();if(!sel.value)sel.value='practice'}

function timerSeconds(timer){if(!timer)return 0;const now=timer.paused&&timer.pausedAt?Number(timer.pausedAt):Date.now();return Math.max(0,Math.floor((now-Number(timer.startedAt))/1000))}
function timerText(timer){const sec=timer.mode==='down'?Math.max(0,Number(timer.durationSec||0)-timerSeconds(timer)):timerSeconds(timer);return `${pad(Math.floor(sec/60))}:${pad(sec%60)}`}
function enhanceTimer(){const state=read(),timer=state?.activeTimer,run=$('#timerRunning');if(run&&!run.querySelector('[data-ux="pause-timer"]')){const finish=run.querySelector('[data-timer="finish"]'),btn=document.createElement('button');btn.type='button';btn.className='btn secondary ux-pause-btn';btn.dataset.ux='pause-timer';btn.style.marginTop='9px';finish?.after(btn)}const btn=run?.querySelector('[data-ux="pause-timer"]');if(btn)btn.textContent=timer?.paused?'继续计时':'暂停';if(timer?.paused){const clock=$('#timerClock');if(clock)clock.textContent=timerText(timer);const status=$('#timerStatus');if(status)status.textContent='已暂停；继续后再完成本次学习';const finish=run?.querySelector('[data-timer="finish"]');if(finish)finish.disabled=true}else{const finish=run?.querySelector('[data-timer="finish"]');if(finish)finish.disabled=false}renderFloatingTimer(state)}
function renderFloatingTimer(state=read()){let bar=$('#uxTimerBar'),timer=state?.activeTimer;if(!timer){bar?.remove();return}const task=(state.tasks||[]).find(t=>t.id===timer.taskId);if(!bar){bar=document.createElement('button');bar.id='uxTimerBar';bar.className='ux-timer-bar';bar.dataset.ux='open-timer';document.body.appendChild(bar)}bar.innerHTML=`<span class="ux-timer-dot">${timer.paused?'Ⅱ':'●'}</span><span class="ux-timer-name">${esc(task?.name||'学习计时')}</span><b>${timerText(timer)}</b><small>${timer.paused?'已暂停':timer.mode==='down'?'倒计时':'正计时'}</small>`}
function toggleTimerPause(){const state=read(),timer=state?.activeTimer;if(!timer)return;if(!timer.paused){timer.paused=true;timer.pausedAt=Date.now();timer.uxPauseUsed=true;write(state);enhanceTimer();toast('计时已暂停')}else{const delta=Date.now()-Number(timer.pausedAt||Date.now());timer.startedAt=Number(timer.startedAt)+Math.max(0,delta);delete timer.pausedAt;timer.paused=false;write(state);sessionStorage.setItem('ux-reopen-timer','1');location.reload()}}
function openFloatingTimer(){sessionStorage.setItem('ux-reopen-timer','1');const nav=$('#nav [data-view="today"]');nav?.click();setTimeout(reopenTimerIfNeeded,80)}
function reopenTimerIfNeeded(){if(sessionStorage.getItem('ux-reopen-timer')!=='1')return;const state=read(),timer=state?.activeTimer;if(!timer){sessionStorage.removeItem('ux-reopen-timer');return}const btn=document.querySelector(`[data-a="start-task"][data-id="${CSS.escape(timer.taskId)}"]`);if(btn){sessionStorage.removeItem('ux-reopen-timer');btn.click()}}

function contextualDeleteTask(id){const state=read(),t=(state?.tasks||[]).find(x=>x.id===id);if(!t)return;if(t.type==='rolling'){toast('滚动任务请在“滚动复习”页完成、顺延或暂停');return}if(!confirm(`删除“${t.name}”？\n日期：${t.date}${t.done?'\n该任务已完成。':''}`))return;stashUndo('任务已删除');if(state.activeTimer?.taskId===id)state.activeTimer=null;if(t.auto){state.customizedDates=state.customizedDates||{};state.customizedDates[t.date]=true}state.tasks=state.tasks.filter(x=>x.id!==id);write(state);location.reload()}

function enhanceAll(){removeLegacyStudyOption();renderRollingEnhanced();todayRollingEnhance();mockTrendEnhance();backupAndCsvEnhance();enhanceTimer();reopenTimerIfNeeded();showUndo()}
let enhancing=false;const observer=new MutationObserver(()=>{if(enhancing)return;enhancing=true;setTimeout(()=>{try{enhanceAll()}finally{enhancing=false}},30)});observer.observe(document.documentElement,{childList:true,subtree:true});
setInterval(()=>{enhanceTimer()},500);

document.addEventListener('click',e=>{
  const ux=e.target.closest('[data-ux]')?.dataset.ux,a=e.target.closest('[data-a]')?.dataset.a,id=e.target.closest('[data-a]')?.dataset.id;
  if(ux==='undo'){e.preventDefault();undo();return}
  if(ux==='select-all'){const checks=$$('.ux-due-check'),on=checks.some(x=>!x.checked);checks.forEach(x=>x.checked=on);return}
  if(ux==='batch-complete')return mutateSelected('complete');if(ux==='batch-delay')return mutateSelected('delay');if(ux==='batch-pause')return mutateSelected('pause');
  if(ux==='toggle-due'){sessionStorage.setItem('ux-roll-expanded',sessionStorage.getItem('ux-roll-expanded')==='1'?'0':'1');const view=$('#view');if(view)delete view.dataset.uxRolling;renderRollingEnhanced();return}
  if(ux==='complete-one')return mutateOne('complete',e.target.closest('[data-ux]').dataset.id,e.target.closest('[data-ux]').dataset.index);
  if(ux==='delay-one')return mutateOne('delay',e.target.closest('[data-ux]').dataset.id,e.target.closest('[data-ux]').dataset.index);
  if(ux==='skip-one')return mutateOne('skip',e.target.closest('[data-ux]').dataset.id,e.target.closest('[data-ux]').dataset.index);
  if(ux==='pause-project')return togglePause(e.target.closest('[data-ux]').dataset.id);if(ux==='delete-project')return deleteRollingProject(e.target.closest('[data-ux]').dataset.id);
  if(ux==='toggle-today'){const v=sessionStorage.getItem('ux-today-roll-expanded')==='1';sessionStorage.setItem('ux-today-roll-expanded',v?'0':'1');$$('.ux-hidden').forEach(x=>x.classList.remove('ux-hidden'));location.reload();return}
  if(ux==='export-csv')return exportCsv();if(ux==='pause-timer')return toggleTimerPause();if(ux==='open-timer')return openFloatingTimer();
  if(a==='del-task'){e.preventDefault();e.stopImmediatePropagation();return contextualDeleteTask(id)}
  if(a==='rolling-delete'){e.preventDefault();e.stopImmediatePropagation();return deleteRollingProject(id)}
  if(['toggle','rolling-complete','rolling-delay','rolling-skip'].includes(a)){stashUndo(a==='toggle'?'任务状态已更新':'滚动复习已更新');setTimeout(showUndo,80)}
  const timer=e.target.closest('[data-timer]')?.dataset.timer;if(['direct','finish'].includes(timer)){stashUndo('学习记录已更新');setTimeout(showUndo,80)}
  if(a==='add-task')setTimeout(()=>{removeLegacyStudyOption();autoTaskName()},20);
},true);
document.addEventListener('change',e=>{if(e.target.id==='tType')autoTaskName()});
document.addEventListener('input',e=>{if(e.target.id==='tName'&&e.isTrusted)e.target.dataset.uxAuto='0'});

enhanceAll();
})();
